export const translations = {
  en: {
    redeemSavings: "Redeem Savings",
    withdrawFunds: "Withdraw funds from your savings account",
    availableBalance: "Available Balance",
    withdrawalTerms: "Withdrawal Terms",
    processingTime: "Processing time: 2–5 business days",
    withdrawalMethod: "Withdrawal Method",
    bankTransfer: "Bank Transfer",
    cashPickup: "Cash Pickup",
    transferToBank: "Transfer to your bank account",
    processing2to3: "Processing: 2–3 business days",
    collectCash: "Collect cash at our location",
    processing1to2: "Processing: 1–2 business days",
    withdrawalAmount: "Withdrawal Amount",
    customAmount: "Custom Amount",
    youWillReceive: "You will receive:",
    noBankAccount: "No bank account added yet.",
    addNewBank: "+ Add New Bank Account",
    accountSettings: "Account Settings",
    language: "Language",
    timeZone: "Time Zone",
  },

  es: {
    redeemSavings: "Canjear Ahorros",
    withdrawFunds: "Retirar fondos de su cuenta de ahorros",
    availableBalance: "Saldo Disponible",
    withdrawalTerms: "Términos de Retiro",
    processingTime: "Tiempo de procesamiento: 2–5 días hábiles",
    withdrawalMethod: "Método de Retiro",
    bankTransfer: "Transferencia Bancaria",
    cashPickup: "Recoger Efectivo",
    transferToBank: "Transferir a su cuenta bancaria",
    processing2to3: "Procesando: 2–3 días hábiles",
    collectCash: "Recoger efectivo en nuestra ubicación",
    processing1to2: "Procesando: 1–2 días hábiles",
    withdrawalAmount: "Monto de Retiro",
    customAmount: "Monto Personalizado",
    youWillReceive: "Usted recibirá:",
    noBankAccount: "Aún no se ha agregado una cuenta bancaria.",
    addNewBank: "+ Agregar nueva cuenta bancaria",
    accountSettings: "Configuración de la Cuenta",
    language: "Idioma",
    timeZone: "Zona horaria",
  },

  fr: {
    redeemSavings: "Retirer des Économies",
    withdrawFunds: "Retirer des fonds de votre compte d'épargne",
    availableBalance: "Solde Disponible",
    withdrawalTerms: "Conditions de Retrait",
    processingTime: "Délai de traitement : 2–5 jours ouvrables",
    withdrawalMethod: "Méthode de Retrait",
    bankTransfer: "Virement Bancaire",
    cashPickup: "Retrait en Espèces",
    transferToBank: "Transférer vers votre compte bancaire",
    processing2to3: "Traitement : 2–3 jours ouvrables",
    collectCash: "Retirer de l'argent à notre emplacement",
    processing1to2: "Traitement : 1–2 jours ouvrables",
    withdrawalAmount: "Montant du Retrait",
    customAmount: "Montant Personnalisé",
    youWillReceive: "Vous recevrez :",
    noBankAccount: "Aucun compte bancaire ajouté pour le moment.",
    addNewBank: "+ Ajouter un nouveau compte bancaire",
    accountSettings: "Paramètres du Compte",
    language: "Langue",
    timeZone: "Fuseau horaire",
  },

  yo: {
    redeemSavings: "Yọ Fọnran",
    withdrawFunds: "Yọ owo kuro ninu iṣura rẹ",
    availableBalance: "Iyọ owo to wa",
    withdrawalTerms: "Ofin yiyọ owo",
    processingTime: "Akoko ṣiṣe: ọjọ iṣowo 2–5",
    withdrawalMethod: "Ọna Yiyọ owo",
    bankTransfer: "Gbigbe si Banki",
    cashPickup: "Gbigba Owo",
    transferToBank: "Gbe si iroyin banki rẹ",
    processing2to3: "Ṣiṣẹ: ọjọ iṣowo 2–3",
    collectCash: "Gba owo ni ibi wa",
    processing1to2: "Ṣiṣẹ: ọjọ iṣowo 1–2",
    withdrawalAmount: "Iye yiyọ owo",
    customAmount: "Iye ti ara rẹ",
    youWillReceive: "Iwọ yoo gba:",
    noBankAccount: "Ko si iroyin banki ti a fi kun sibẹsibẹ.",
    addNewBank: "+ Ṣafikun iroyin banki tuntun",
    accountSettings: "Eto iroyin",
    language: "Ede",
    timeZone: "Aago agbegbe",
  },
};
